package archivo;

import javax.swing.JOptionPane;

public class VentanaRegistros extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaRegistros() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de denuncias");
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldCorreo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        bg = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        labelDetalles = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldCorreo = new javax.swing.JTextField();
        textFieldDomicilio = new javax.swing.JTextField();
        buttonGuardar = new javax.swing.JButton();
        cbTipoFeedback = new javax.swing.JComboBox<>();
        labelFeedback = new javax.swing.JLabel();
        labelAtencionc = new javax.swing.JLabel();
        labelSistemaN = new javax.swing.JLabel();
        labelImagen2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelImagen1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDetalles = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelNombre.setBackground(new java.awt.Color(0, 0, 0));
        labelNombre.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setText("NOMBRE");
        bg.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        labelTelefono.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(0, 0, 0));
        labelTelefono.setText("TELÉFONO");
        bg.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        labelDomicilio.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        labelDomicilio.setForeground(new java.awt.Color(0, 0, 0));
        labelDomicilio.setText("DOMICILIO / UBICACIÓN");
        bg.add(labelDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        labelDetalles.setBackground(new java.awt.Color(0, 0, 0));
        labelDetalles.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        labelDetalles.setForeground(new java.awt.Color(0, 0, 0));
        labelDetalles.setText("DETALLES");
        bg.add(labelDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        labelCorreo.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelCorreo.setForeground(new java.awt.Color(0, 0, 0));
        labelCorreo.setText("E-MAIL");
        bg.add(labelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        textFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        textFieldNombre.setBorder(null);
        textFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreActionPerformed(evt);
            }
        });
        bg.add(textFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 217, -1));

        textFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        textFieldTelefono.setBorder(null);
        textFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTelefonoActionPerformed(evt);
            }
        });
        bg.add(textFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 217, -1));

        textFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        textFieldCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldCorreo.setBorder(null);
        bg.add(textFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 217, -1));

        textFieldDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        textFieldDomicilio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFieldDomicilio.setBorder(null);
        textFieldDomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDomicilioActionPerformed(evt);
            }
        });
        bg.add(textFieldDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 217, -1));

        buttonGuardar.setBackground(new java.awt.Color(0, 134, 190));
        buttonGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        buttonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        buttonGuardar.setText("GUARDAR");
        buttonGuardar.setBorder(null);
        buttonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGuardarActionPerformed(evt);
            }
        });
        bg.add(buttonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 130, 40));

        cbTipoFeedback.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoFeedback.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbTipoFeedback.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Queja", "Denuncia", "Reclamación", "Sugerencia" }));
        cbTipoFeedback.setBorder(null);
        cbTipoFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoFeedbackActionPerformed(evt);
            }
        });
        bg.add(cbTipoFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 217, -1));

        labelFeedback.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelFeedback.setForeground(new java.awt.Color(0, 0, 0));
        labelFeedback.setText("TIPO DE FEEDBACK");
        bg.add(labelFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        labelAtencionc.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        labelAtencionc.setForeground(new java.awt.Color(255, 255, 255));
        labelAtencionc.setText("DE ATENCIÓN CIUDADANA");
        bg.add(labelAtencionc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        labelSistemaN.setBackground(new java.awt.Color(255, 255, 255));
        labelSistemaN.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        labelSistemaN.setForeground(new java.awt.Color(255, 255, 255));
        labelSistemaN.setText("SISTEMA NACIONAL");
        bg.add(labelSistemaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        labelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-311.png"))); // NOI18N
        bg.add(labelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("REGISTRO DE DENUNCIAS");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        labelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/city.png"))); // NOI18N
        bg.add(labelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -40, 290, 580));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 210, -1));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 210, -1));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 210, -1));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 210, -1));

        textAreaDetalles.setBackground(new java.awt.Color(255, 255, 255));
        textAreaDetalles.setColumns(20);
        textAreaDetalles.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textAreaDetalles.setRows(5);
        textAreaDetalles.setBorder(null);
        jScrollPane1.setViewportView(textAreaDetalles);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, 200));

        jMenu1.setText("Menú");

        jMenuItem2.setText("Mostrar registros");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void textFieldDomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDomicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDomicilioActionPerformed

    private void buttonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGuardarActionPerformed
        // TODO add your handling code here:
        Archivo archivo = new Archivo();
        archivo.crearArchivos();

        if (textFieldNombre.getText().equals("") || textFieldTelefono.getText().equals("") || textFieldTelefono.getText().equals("")
                || textAreaDetalles.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Rellene los campos");
        } else {
            
            String tipoFeedback = (String) cbTipoFeedback.getSelectedItem();

            String nombre = textFieldNombre.getText();
            String telefono = textFieldTelefono.getText();
            String correo = textFieldCorreo.getText();
            String domicilio = textFieldDomicilio.getText();
            String detalles = textAreaDetalles.getText();

            Denuncia denuncia = new Denuncia(nombre, telefono, correo, domicilio, detalles, tipoFeedback);
            archivo.escribirEnArchivo(denuncia);

            JOptionPane.showMessageDialog(null, "Registro guardado");
        }
        
    }//GEN-LAST:event_buttonGuardarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VentanaDenunciasRegistradas registrosD = new VentanaDenunciasRegistradas();
        this.setVisible(false);
        registrosD.setVisible(true);
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void textFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldTelefonoActionPerformed

    private void cbTipoFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoFeedbackActionPerformed
        // TODO add your handling code here:
        String tipoFeedback = (String) cbTipoFeedback.getSelectedItem();
        
       textAreaDetalles.setEnabled(false);
        labelDetalles.setEnabled(false);
        textFieldDomicilio.setEnabled(false);
        labelDomicilio.setEnabled(false);

        switch (tipoFeedback) {
        // Mostrar campos específicos para quejas y ocultar otros
        // Puedes habilitar/deshabilitar campos según sea necesario
            case "Queja":
                textAreaDetalles.setEnabled(true);
                labelDetalles.setEnabled(true);
                break;
        // Mostrar campos específicos para denuncias y ocultar otros
            case "Denuncia":
                 textAreaDetalles.setEnabled(true);
                 labelDetalles.setEnabled(true);
                textFieldDomicilio.setEnabled(true);
                 labelDomicilio.setEnabled(true);
                break;
        // Mostrar campos específicos para reclamaciones y ocultar otros
            case "Reclamación":
                textAreaDetalles.setEnabled(true);
                labelDetalles.setEnabled(true);
                break;
        // Mostrar campos específicos para sugerencias y ocultar otros
            case "Sugerencia":
                 textAreaDetalles.setEnabled(true);
                 labelDetalles.setEnabled(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbTipoFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buttonGuardar;
    private javax.swing.JComboBox<String> cbTipoFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelAtencionc;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDetalles;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelFeedback;
    private javax.swing.JLabel labelImagen1;
    private javax.swing.JLabel labelImagen2;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelSistemaN;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTextArea textAreaDetalles;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldCorreo1;
    private javax.swing.JTextField textFieldDomicilio;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
