package archivo;

import java.io.File;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

public class VentanaDenunciasRegistradas extends javax.swing.JFrame {

     DefaultTableModel modeloQuejas = new DefaultTableModel();
    DefaultTableModel modeloDenuncias = new DefaultTableModel();
    DefaultTableModel modeloReclamaciones = new DefaultTableModel();
    DefaultTableModel modeloSugerencias = new DefaultTableModel();
    
    
    
    public VentanaDenunciasRegistradas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registros guardados");
        this.setResizable(false);
        cargarModelos();
    }
    
    private void cargarModelos() {
        cargarModelo("Queja", modeloQuejas);
        cargarModelo("Denuncia", modeloDenuncias);
        cargarModelo("Reclamación", modeloReclamaciones);
        cargarModelo("Sugerencia", modeloSugerencias);
    }

    private void cargarModelo(String tipoFeedback, DefaultTableModel modelo) {
        try {
            modelo.addColumn("Nombre");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");
            modelo.addColumn("Domicilio");
            modelo.addColumn("Detalles");

            switch (tipoFeedback) {
                case "Queja":
                    tableQuejas.setModel(modelo);
                    break;
                case "Denuncia":
                    tableDenuncias.setModel(modelo);
                    break;
                case "Reclamación":
                    tableReclamaciones.setModel(modelo);
                    break;
                case "Sugerencia":
                    tableSugerencias.setModel(modelo);
                    break;
                default:
                    throw new IllegalArgumentException("Tipo de feedback no válido: " + tipoFeedback);
            }

            cargarArchivo(tipoFeedback, modelo);

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    private void cargarArchivo(String tipoFeedback, DefaultTableModel modelo) throws IOException {
        String fila[];

        File archivo;
        switch (tipoFeedback) {
            case "Queja":
                archivo = new File("Quejas.txt");
                break;
            case "Denuncia":
                archivo = new File("Denuncias.txt");
                break;
            case "Reclamación":
                archivo = new File("Reclamaciones.txt");
                break;
            case "Sugerencia":
                archivo = new File("Sugerencias.txt");
                break;
            default:
                throw new IllegalArgumentException("Tipo de feedback no válido: " + tipoFeedback);
        }

        try {
            FileReader archivoReader = new FileReader(archivo);
            BufferedReader lectura = new BufferedReader(archivoReader);

            String linea = lectura.readLine();

            while (linea != null) {
                fila = linea.split("%");
                modelo.addRow(fila);
                linea = lectura.readLine();
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuejas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buttonAtras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDenuncias = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableReclamaciones = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableSugerencias = new javax.swing.JTable();
        labelQuejas = new javax.swing.JLabel();
        labelDenuncias = new javax.swing.JLabel();
        labelReclamaciones = new javax.swing.JLabel();
        labelSugerencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableQuejas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableQuejas);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 563, 260));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("SISTEMA DE ATENCIÓN CIUDADANA");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        buttonAtras.setBackground(new java.awt.Color(255, 255, 255));
        buttonAtras.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        buttonAtras.setForeground(new java.awt.Color(102, 102, 102));
        buttonAtras.setText("ATRÁS");
        buttonAtras.setBorder(null);
        buttonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtrasActionPerformed(evt);
            }
        });
        bg.add(buttonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 30));

        tableDenuncias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDenuncias);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 563, 260));

        tableReclamaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableReclamaciones);

        bg.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 563, 260));

        tableSugerencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableSugerencias);

        bg.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 563, 260));

        labelQuejas.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelQuejas.setForeground(new java.awt.Color(0, 0, 0));
        labelQuejas.setText("QUEJAS");
        bg.add(labelQuejas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        labelDenuncias.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelDenuncias.setForeground(new java.awt.Color(0, 0, 0));
        labelDenuncias.setText("DENUNCIAS");
        bg.add(labelDenuncias, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        labelReclamaciones.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelReclamaciones.setForeground(new java.awt.Color(0, 0, 0));
        labelReclamaciones.setText("RECLAMACIONES");
        bg.add(labelReclamaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        labelSugerencias.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        labelSugerencias.setForeground(new java.awt.Color(0, 0, 0));
        labelSugerencias.setText("SUGERENCIAS");
        bg.add(labelSugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAtrasActionPerformed
        // TODO add your handling code here:
        VentanaRegistros registros = new VentanaRegistros();
        this.setVisible(false);
        registros.setVisible(true);
        
    }//GEN-LAST:event_buttonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDenunciasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDenunciasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDenunciasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDenunciasRegistradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDenunciasRegistradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton buttonAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelDenuncias;
    private javax.swing.JLabel labelQuejas;
    private javax.swing.JLabel labelReclamaciones;
    private javax.swing.JLabel labelSugerencias;
    private javax.swing.JTable tableDenuncias;
    private javax.swing.JTable tableQuejas;
    private javax.swing.JTable tableReclamaciones;
    private javax.swing.JTable tableSugerencias;
    // End of variables declaration//GEN-END:variables
}
